config/routes.rb
Rails.application.routes.draw do
  resources :worker_farms, only: :show
  resources :farms
  resources :workers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/farm.rb
class Farm < ApplicationRecord

    has_many :worker_farms 
    has_many :workers, through: :worker_farms

    accepts_nested_attributes_for :workers

end

app/models/worker.rb
class Worker < ApplicationRecord

    has_many :worker_farms 
    has_many :farms, through: :worker_farms
end

app/models/worker_farm.rb
class WorkerFarm < ApplicationRecord

    belongs_to :worker 
    belongs_to :farm 


    

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/farms_controller.rb
class FarmsController < ApplicationController
    def index 
        @farms = Farm.all 
    end 

    def show 
        @farm = Farm.find(params[:id])
    end 

    def new
        @farm = Farm.new
        @farm.workers.build()
    end 

    def create 
        @farm = Farm.create(farm_params)
        redirect_to farm_path(@farm)
    end 

    def edit 
        @farm = Farm.find(params[:id])
    end 

    def update 
        @farm = Farm.find(params[:id])
        @farm.update(farm_params)
        redirect_to farm_path(@farm)
    end 

    def destroy
        Farm.destroy(params[:id])
        redirect_to farms_path
    end 



private 

def farm_params 
    params.require(:farm).permit(:name, :farm_type, :acres, workers_attributes: [:name, :yrs_experience], worker_ids:[])
end 



end

app/controllers/worker_farms_controller.rb
class WorkerFarmsController < ApplicationController

    def show 

    end 


end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController

    def index 
        @workers = Worker.all 
    end 

    def show 
        @worker = Worker.find(params[:id])
    end 

    def new
        @worker = Worker.new
    end 

    def create 
        @worker = Worker.create(worker_params)
        redirect_to worker_path(@worker)
    end 

    def edit 
        @worker = Worker.find(params[:id])
    end 

    def update 
        @worker = Worker.find(params[:id])
        @worker.update(worker_params)
        redirect_to worker_path(@worker)
    end 

    def destroy
        Worker.destroy(params[:id])
        redirect_to workers_path
    end 



private 

def worker_params 
    params.require(:worker).permit(:name, :yrs_experience, farm_ids:[])
end 


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/farms_helper.rb
module FarmsHelper
end

app/helpers/worker_farms_helper.rb
module WorkerFarmsHelper
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/farms/edit.html.erb
<%= form_for @farm do |f|%>
    <%=f.label :name%>
    <%=f.text_field :name%> <br>

    <%=f.label :Type_of_Farm%>
    <%=f.text_field :farm_type%>

    <%=f.label :Acres%>
    <%=f.number_field :acres%>

    <br>
    Select Workers to Hire or Deselect Workers to Fire: <br>
    <%= f.collection_check_boxes :worker_ids, Worker.all, :id, :name  %>
    <br>


    <%=f.submit "Edit Farm"%>
<%end%>

app/views/farms/index.html.erb
<h1>Farm Index Page</h1>

<ul>
<%@farms.each do |farm|%>
    <li><%=link_to farm.name, farm_path(farm)%></li>
<%end%>
</ul>
<br>

<%= link_to "Build a New Farm", new_farm_path%>

app/views/farms/new.html.erb
<%= form_for @farm do |f|%>
    <%=f.label :name%>
    <%=f.text_field :name%> <br>

    <%=f.label :Type_of_Farm%>
    <%=f.text_field :farm_type%> <br>

    <%=f.label :Acres%>
    <%=f.number_field :acres%> <br>
            Create Worker: <br>
        <%= f.fields_for :workers do |w| %>
                <%=w.label :name%>
                <%=w.text_field :name%> <br>
            
                <%=w.label :Years_of_Experience%>
                <%=w.number_field :yrs_experience%>

        <%end%>

    <%=f.submit "Build New Farm"%>
<%end%>

app/views/farms/show.html.erb
<h1><%=@farm.name%></h1>

<h3>Farm Type: <%=@farm.farm_type%></h3>
<h3>Acres: <%=@farm.acres%></h3> <br>
<h3>Farm Workers: <ul> <%@farm.workers.each do |worker| %>
    <li><%= link_to worker.name, worker_path(worker) %></li>
    <%end%>
    </ul>
<br>

<%=link_to "Farm Index Page", farms_path%> <br>
<%=link_to "Edit this Farm", edit_farm_path(@farm)%> <br>
<%=link_to "Delete this Farm", farm_path(@farm), "method" => :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FarmHouse</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/workers/edit.html.erb
<%= form_for @worker do |w|%>
    <%=w.label :name%>
    <%=w.text_field :name%> <br>

    <%=w.label :Years_of_Experience%>
    <%=w.number_field :yrs_experience%>
    <br>
    Select Farms To Work For: <br>
    <%= w.collection_check_boxes :farm_ids, Farm.all, :id, :name  %>

<br>



    <%=w.submit "Update Worker"%>
<%end%>

app/views/workers/index.html.erb
<h1>Worker Index Page</h1>

<ul>
<%@workers.each do |worker|%>
    <li><%=link_to worker.name, worker_path(worker)%></li>
<%end%>
</ul>

<%= link_to "Register New Worker", new_worker_path%>

app/views/workers/new.html.erb
<%= form_for @worker do |w|%>
    <%=w.label :name%>
    <%=w.text_field :name%> <br>

    <%=w.label :Years_of_Experience%>
    <%=w.number_field :yrs_experience%> <br>
 Select Farms To Work For: <br>
    <%= w.collection_check_boxes :farm_ids, Farm.all, :id, :name  %>

<br>
    <%=w.submit "Register New Worker"%>
<%end%>

app/views/workers/show.html.erb
<h1><%=@worker.name%></h1>

<h3>Experience: <%=@worker.yrs_experience%></h3>
<br>
<h3>Farms Working For: <ul> <%@worker.farms.each do |farm| %>
    <li><%= link_to farm.name, farm_path(farm) %></li>
    <%end%>
    </ul>
<br>

<%=link_to "Worker Index Page", workers_path%>
<br> 

<%=link_to "Edit this Worker", edit_worker_path(@worker)%>
<br>

<%=link_to "Terminate Employment", worker_path(@worker), 'method' => :delete %>